theme = "ayu_mirage"

[editor]
true-color = true
line-number = "relative"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"

[keys.normal]
C-s = ":w"
"ret" = ["open_below", "normal_mode"]


[keys.insert]
j = {k = "normal_mode"}
